### ISSUE TITLE
[OTP 18] meck fails on modules with map types

### ISSUE THREAD

**Issue by ElectronicRU** [eproxus/meck#166] opened 2016-08-15 13:10 UTC
When trying to mock a module that contains erl_lint attributes linked to map types, meck crashes.
## Reproduction Steps
1. Create a module with a non-empty map type (e.g. #{binary()=>binary()}).
2. Compile it under OTP 18 (18.3 in my case).
3. Try to mock it.
## Expected behavior

The mocking proceeds as normal.
## Observed behavior

Meck crashes with {compile_form, <...> [{_, erl_lint, {type_syntax, integer}}]}.
## Versions

**Meck version:** 0.8.4
**Erlang version:** 18.3

**Comment by eproxus** [comment] 2017-02-13 12:59
I cannot reproduce this bug in 18.3 or 19.2 (see the mentioned branch). Closing for now.

Please re-open if it is still an issue!

**Closed by eproxus** 2017-02-13 12:59 UTC
